### PR TITLE
docs: added workflows readme

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

Added a new README to the workflows directory to explain usage of reusable common workflows.

**Check the relevant boxes:**
- [ ] Bug fix (nonbreaking change that fixes an issue)
- [ ] New feature (nonbreaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Examples or tests (addition or updates of examples or tests)
- [x] Documentation update
- [ ] CI related update (pipeline, etc.)

### Checklist

- [ ] If relevant, a test for the change has been added or updated as part of this PR.
- [x] If relevant, documentation for the change has been added or updated as part of this PR.

### Merge

- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

### CODE REVIEW

**Review by ocofaigh — COMMENTED** [review]
Can we add this to common-pipeline-assets instead so we only have 1 place to maintain it? Otherwise this will end up in every repo as new repos are cloned from this template

**Comment by ocofaigh** [comment]
Oh I see @SirSpidey created a doc repo. Maybe it should live there? https://github.com/terraform-ibm-modules/documentation

**Comment by SirSpidey** [comment]
We can add a section for "internal" or maintainer content if you want. Docs are rendered now at https://terraform-ibm-modules.github.io/documentation/ (still a big WIP).

**Comment by SirSpidey** [comment]
Closing this in favor of https://github.com/terraform-ibm-modules/documentation/pull/5

**Pull request closed without merging**
