### PR TITLE
ci: enables cra-scan

### PR DESCRIPTION
**Pull request by iamar7**
### Description

Enable CRA scanning for terraform-ibm-module-template

### Types of changes in this PR

https://github.ibm.com/GoldenEye/issues/issues/4120

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [x] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
I do not want to have anything in the cra-tf-validate-ignore-goals.json file in our module template. So if that means we need to change the example to something that passes CRA scan, lets do that.

**Comment by iamar7** [comment]
> I do not want to have anything in the cra-tf-validate-ignore-goals.json file in our module template. So if that means we need to change the example to something that passes CRA scan, lets do that.

Made the necessary changes.

**Review by ocofaigh — CHANGES_REQUESTED** [review]
replace the `default` example with the `non-vpc` example you just added. That should do fine for module template I think

**Comment by iamar7** [comment]
> replace the `default` example with the `non-vpc` example you just added. That should do fine for module template I think

I did that previously in this [commit](https://github.com/terraform-ibm-modules/terraform-ibm-module-template/pull/446/commits/e7cbda6083f60e5a94a6edae0babd685799b6616) but the build module template pre-commit hooks were modifying the `main.tf` of **default** example. So I checked the [moduleTemplateBuilder.py](https://github.com/terraform-ibm-modules/common-dev-assets/blob/7d9cc29b4d702fc51cb84c6193d3ab7534f3e127/module-assets/ci/module-template-automation/moduleTemplateBuilder.py) where we can see that the script is pasting the examples from [module-template-automation](https://github.com/terraform-ibm-modules/common-dev-assets/tree/7d9cc29b4d702fc51cb84c6193d3ab7534f3e127/module-assets/ci/module-template-automation/examples) folder.

**Comment by ocofaigh** [comment]
Ahh yes, we need to make this change in https://github.com/terraform-ibm-modules/common-dev-assets/tree/main/module-assets/ci/module-template-automation/examples

**Comment by iamar7** [comment]
> 

made the changes as suggested.

**Comment by iamar7** [comment]
> Ahh yes, we need to make this change in https://github.com/terraform-ibm-modules/common-dev-assets/tree/main/module-assets/ci/module-template-automation/examples

made the changes as suggested.

**Comment by iamar7** [comment]
> > Ahh yes, we need to make this change in https://github.com/terraform-ibm-modules/common-dev-assets/tree/main/module-assets/ci/module-template-automation/examples
> 
> made the changes as suggested.

After making those changes the `terraform apply` was passing on the **`default example`** but `make run-tests-local RUN` is failing because it is taking `resource_tag` as empty input. On further investigation, I found that we are passing the empty resource tag from [here](https://github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper/blob/303288d95c7619c665ff48b67b313a27c3d6f1ee/testhelper/test_options.go#L157). **Can you suggest what should be done regarding this**?


Screenshot 2023-03-20 at 2 40 34 PM

**Comment by ocofaigh** [comment]
@iamar7 perhaps we create an example that does provision something that a resource tag can be passed into, but ensure the example passes CRA. Something quick like a COS instance perhaps?

**Comment by iamar7** [comment]
> @iamar7 perhaps we create an example that does provision something that a resource tag can be passed into, but ensure the example passes CRA. Something quick like a COS instance perhaps?

Yes, I added that.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
